---
- hosts: webservers
  become: yes
  tasks:
#-----------------------------------------------------------
    - name: Put SELinux in permissive mode, logging actions that would be blocked.
      selinux:
        policy: targeted
        state: permissive
#-----------------------------------------------------------
    - name: Installing Java
      yum:
        name:
         - java-1.8.0-openjdk
#-----------------------------------------------------------
    - name: Add elastic repository
      yum_repository:
        name: Elastic
        description: Official Elastic repository
        baseurl: "https://artifacts.elastic.co/downloads/elasticsearch-6.2.3.rpm"
        gpgkey:  "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
        gpgcheck: true
      tags: elastic
#----------------------------------------------------------

    - name: elasticsearch & logstash & kibana installation
      yum:
        name:
                - https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.2.0-x86_64.rpm
                - https://artifacts.elastic.co/downloads/logstash/logstash-7.2.0.rpm
                - https://artifacts.elastic.co/downloads/kibana/kibana-6.2.0-x86_64.rpm
#-----------------------------------------------------------
